// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMb689FjQDn_SV2h6lJvkYDnveQMsbq8I',
    appId: '1:264005611904:web:869a70d06546fcf39e5165',
    messagingSenderId: '264005611904',
    projectId: 'autopark-c34b2',
    authDomain: 'autopark-c34b2.firebaseapp.com',
    storageBucket: 'autopark-c34b2.appspot.com',
    measurementId: 'G-YL6FL620SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwjq_FnHJaZIek4CjrcBwuMHJFu6ef03g',
    appId: '1:264005611904:android:fac2c793ffa318969e5165',
    messagingSenderId: '264005611904',
    projectId: 'autopark-c34b2',
    storageBucket: 'autopark-c34b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCciKt2pw6tHsfYeKcgd2Kg3iGNRk6gADc',
    appId: '1:264005611904:ios:e0ee75761f55ab0e9e5165',
    messagingSenderId: '264005611904',
    projectId: 'autopark-c34b2',
    storageBucket: 'autopark-c34b2.appspot.com',
    iosClientId: '264005611904-oibsbf8aohgke4evfnmjnnhrmdb6v3qu.apps.googleusercontent.com',
    iosBundleId: 'com.example.automatedParking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCciKt2pw6tHsfYeKcgd2Kg3iGNRk6gADc',
    appId: '1:264005611904:ios:fa6118f7fc96f0559e5165',
    messagingSenderId: '264005611904',
    projectId: 'autopark-c34b2',
    storageBucket: 'autopark-c34b2.appspot.com',
    iosClientId: '264005611904-7de8mm7j17j6i29dn86k5ivuq50l1on9.apps.googleusercontent.com',
    iosBundleId: 'com.example.automatedParking.RunnerTests',
  );
}
